<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>psn.austus</groupId>
    <artifactId>austus-frame-parent</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>${project.artifactId}</name>
    <description>对jar版本，仓库进行管理</description>
    <packaging>pom</packaging>

    <modules>
        <module>austus-frame-dependencies</module>
        <!--<module>austus-frame-commons</module>-->
    </modules>

</project>